#!/usr/bin/env python3
"""Auto-generate the game include + detection lists for JaffarPlus by scanning games/.

Every game header is `jaffarPlus::games::<dir>::<Class> final : public jaffarPlus::Game`,
so we glob games/**/*.hpp, parse the class name, and derive the platform #if guard from the
directory (with a few cross-platform/sub-feature overrides). Emits two generated headers that
gameList.hpp includes: the #include block and the DETECT_GAME block. Adding a game in a known
platform dir requires no edits here -- just re-run meson setup.

Usage: genGameList.py <games_dir> <out_includes.hpp> <out_detect.hpp>
"""
import os, re, sys, glob

# platform directory -> preprocessor guard (matches emulators/meson.build defines)
DIR_GUARD = {
    "nes":     "defined(__JAFFAR_ENABLE_NES)",
    "sdlpop":  "defined(__JAFFAR_ENABLE_SDLPOP)",
    "snes":    "defined(__JAFFAR_ENABLE_SNES)",
    "genesis": "defined(__JAFFAR_ENABLE_GENESIS)",
    "gamegear":"defined(__JAFFAR_ENABLE_GENESIS)",
    "sms":     "defined(__JAFFAR_ENABLE_GENESIS)",
    "a2600":   "defined(__JAFFAR_ENABLE_A2600)",
    "raw":     "(defined(__JAFFAR_ENABLE_NEORAW) || defined(__JAFFAR_ENABLE_RAWGL))",
    "arkbot":  "defined(__JAFFAR_USE_ARKBOT)",
    "gba":     "defined(__JAFFAR_ENABLE_GBA)",
    "gbc":     "defined(__JAFFAR_ENABLE_GBC)",
    "doom":    "defined(__JAFFAR_ENABLE_DOOM)",
    "pipeBot": "defined(__JAFFAR_ENABLE_PIPEBOT)",
    "test":    "defined(__JAFFAR_ENABLE_TESTGAME)",
}
# per-file overrides (cross-platform / sub-feature games)
FILE_GUARD = {
    "nes/superMarioBros.hpp": "(defined(__JAFFAR_ENABLE_SMBC) || defined(__JAFFAR_ENABLE_NES))",
    "nes/arkanoid2.hpp":      "defined(__JAFFAR_USE_QUICKERNES_ARKANOID)",
}
CLASS_RE = re.compile(r"class\s+(\w+)\s+final\s*:\s*public\s+jaffarPlus::Game")

def collect(games_dir):
    out = []
    for hpp in sorted(glob.glob(os.path.join(games_dir, "**", "*.hpp"), recursive=True)):
        rel = os.path.relpath(hpp, games_dir).replace(os.sep, "/")
        if rel == "gameList.hpp": continue
        m = CLASS_RE.search(open(hpp).read())
        if not m: continue                       # not a game header
        ns  = rel.split("/")[0]
        cls = m.group(1)
        guard = FILE_GUARD.get(rel) or DIR_GUARD.get(ns)
        if guard is None:
            sys.stderr.write(f"[genGameList] WARNING: no guard for dir '{ns}' ({rel}) -- skipped\n")
            continue
        out.append((guard, rel, ns, cls))
    return out

def main():
    games_dir, out_inc, out_det = sys.argv[1], sys.argv[2], sys.argv[3]
    entries = collect(games_dir)
    with open(out_inc, "w") as f:
        f.write("// AUTO-GENERATED by genGameList.py -- do not edit.\n#pragma once\n")
        for guard, rel, ns, cls in entries:
            f.write(f"#if {guard}\n#include \"{rel}\"\n#endif\n")
    with open(out_det, "w") as f:
        f.write("// AUTO-GENERATED by genGameList.py -- do not edit.\n")
        for guard, rel, ns, cls in entries:
            f.write(f"#if {guard}\n  DETECT_GAME({ns}::{cls})\n#endif\n")
    sys.stderr.write(f"[genGameList] {len(entries)} games -> {out_inc}, {out_det}\n")

if __name__ == "__main__":
    main()
