#!/usr/bin/env python3
"""Auto-generate the include + detection lists for JaffarPlus games and emulators.

Both games and emulators follow a uniform shape -- `class <X> final : public <Base>` inside a
known namespace, selected by a platform/use preprocessor guard. This globs the relevant tree,
parses each class name, derives the guard from the directory, and emits two generated headers
(an #include block and a DETECT_* block) that gameList.hpp / emulatorList.hpp #include. Adding a
game/emulator header needs no manual list edits -- just re-run `meson setup`.

Usage:
  genRegistry.py games     <gamesDir>     <out_includes> <out_detect> [singleGameFilter]
  genRegistry.py emulators <emulatorsDir> <out_includes> <out_detect>
"""
import os, re, sys, glob

# --- games: directory -> platform guard, plus per-file cross-platform/sub-feature overrides ---
GAME_DIR_GUARD = {
    "nes":"defined(__JAFFAR_ENABLE_NES)", "sdlpop":"defined(__JAFFAR_ENABLE_SDLPOP)",
    "snes":"defined(__JAFFAR_ENABLE_SNES)", "genesis":"defined(__JAFFAR_ENABLE_GENESIS)",
    "gamegear":"defined(__JAFFAR_ENABLE_GENESIS)", "sms":"defined(__JAFFAR_ENABLE_GENESIS)",
    "a2600":"defined(__JAFFAR_ENABLE_A2600)",
    "raw":"(defined(__JAFFAR_ENABLE_NEORAW) || defined(__JAFFAR_ENABLE_RAWGL))",
    "arkbot":"defined(__JAFFAR_USE_ARKBOT)", "gba":"defined(__JAFFAR_ENABLE_GBA)",
    "gbc":"defined(__JAFFAR_ENABLE_GBC)", "doom":"defined(__JAFFAR_ENABLE_DOOM)",
    "pipeBot":"defined(__JAFFAR_ENABLE_PIPEBOT)", "test":"defined(__JAFFAR_ENABLE_TESTGAME)",
}
GAME_FILE_GUARD = {
    "nes/superMarioBros.hpp":"(defined(__JAFFAR_ENABLE_SMBC) || defined(__JAFFAR_ENABLE_NES))",
    "nes/arkanoid2.hpp":"defined(__JAFFAR_USE_QUICKERNES_ARKANOID)",
}
# --- emulators: directory -> use guard is __JAFFAR_USE_<UPPER(dir)>, with one override ---
EMU_GUARD_OVERRIDE = {"quickerArkBot": "__JAFFAR_USE_ARKBOT"}

def game_guard(rel, d):  return GAME_FILE_GUARD.get(rel) or GAME_DIR_GUARD.get(d)
def emu_guard(rel, d):   return "defined(%s)" % EMU_GUARD_OVERRIDE.get(d, "__JAFFAR_USE_" + d.upper())

KIND = {
    "games":     dict(base="jaffarPlus::Game", macro="DETECT_GAME",     ns="dir",      guard=game_guard, filterable=True),
    "emulators": dict(base="Emulator",         macro="DETECT_EMULATOR", ns="emulator", guard=emu_guard,  filterable=False),
}

def main():
    kind, root, out_inc, out_det = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
    filt = (sys.argv[5] if len(sys.argv) > 5 else "").strip()
    cfg = KIND[kind]
    class_re = re.compile(r"class\s+(\w+)\s+final\s*:\s*public\s+" + re.escape(cfg["base"]) + r"\b")
    entries = []
    for hpp in sorted(glob.glob(os.path.join(root, "**", "*.hpp"), recursive=True)):
        rel = os.path.relpath(hpp, root).replace(os.sep, "/")
        m = class_re.search(open(hpp).read())
        if not m: continue                                   # not a registrable class (list/helper headers skipped)
        cls, d = m.group(1), rel.split("/")[0]
        if cfg["filterable"] and filt and os.path.splitext(os.path.basename(rel))[0].lower() != filt.lower():
            continue                                          # -Dgame=<stem>: keep only the matching header
        guard = cfg["guard"](rel, d)
        if guard is None:
            sys.stderr.write(f"[genRegistry] WARNING: no guard for '{rel}' -- skipped\n"); continue
        ns = d if cfg["ns"] == "dir" else cfg["ns"]
        entries.append((guard, rel, ns, cls))
    with open(out_inc, "w") as f:
        f.write("// AUTO-GENERATED by genRegistry.py -- do not edit.\n#pragma once\n")
        for guard, rel, ns, cls in entries: f.write(f"#if {guard}\n#include \"{rel}\"\n#endif\n")
    with open(out_det, "w") as f:
        f.write("// AUTO-GENERATED by genRegistry.py -- do not edit.\n")
        for guard, rel, ns, cls in entries: f.write(f"#if {guard}\n  {cfg['macro']}({ns}::{cls})\n#endif\n")
    sys.stderr.write(f"[genRegistry] {kind}: {len(entries)} entries"
                     + (f" (filtered to '{filt}')" if filt else "") + f" -> {out_inc}, {out_det}\n")

if __name__ == "__main__":
    main()
