jaffar script0; cp /tmp/jaffar.best.sol full0
jaffar script1; cp /tmp/jaffar.best.sol full1
jaffar script2; cp /tmp/jaffar.best.sol full2
jaffar script3; cp /tmp/jaffar.best.sol full3
jaffar script4; cp /tmp/jaffar.best.sol full4
jaffar script5; cp /tmp/jaffar.best.sol full5
jaffar script6; cp /tmp/jaffar.best.sol full6
jaffar script7; cp /tmp/jaffar.best.sol full7
jaffar script8; cp /tmp/jaffar.best.sol full8
jaffar script9; cp /tmp/jaffar.best.sol full9
jaffar script10; cp /tmp/jaffar.best.sol full10
jaffar script11; cp /tmp/jaffar.best.sol full11
jaffar script12; cp /tmp/jaffar.best.sol full12
jaffar script13; cp /tmp/jaffar.best.sol full13
